CONTIKI = ../../../../..
CASAN = ../..
PROJECT_SOURCEFILES += $(CASAN)/libraries/ConMsg/ConMsg.c
TARGET = iotlab-m3


all:	test1 test2 ../../libraries/ConMsg/ConMsg

include $(CONTIKI)/Makefile.include



